// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBemXS98efxHG2jg4nQMlBgkEo-kI0D4Qc',
    appId: '1:970265271987:web:1abe309fd64c186d8c5ac6',
    messagingSenderId: '970265271987',
    projectId: 'projectsima',
    authDomain: 'projectsima.firebaseapp.com',
    storageBucket: 'projectsima.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-PxbBL37Ssx9q8EwEa9hbi0MPB6-MH9U',
    appId: '1:970265271987:android:7be9f3c6ad3fbce38c5ac6',
    messagingSenderId: '970265271987',
    projectId: 'projectsima',
    storageBucket: 'projectsima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkwIeavAwNuXjfyvJbsnF9kbJBT49ay8E',
    appId: '1:970265271987:ios:7abecd00add39c928c5ac6',
    messagingSenderId: '970265271987',
    projectId: 'projectsima',
    storageBucket: 'projectsima.appspot.com',
    iosBundleId: 'com.example.simaApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkwIeavAwNuXjfyvJbsnF9kbJBT49ay8E',
    appId: '1:970265271987:ios:fbd7eafa9471c1638c5ac6',
    messagingSenderId: '970265271987',
    projectId: 'projectsima',
    storageBucket: 'projectsima.appspot.com',
    iosBundleId: 'com.example.simaApp1.RunnerTests',
  );
}
